[package]
name = "rustakl_sever"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.39", features = ["rt-multi-thread", "macros", "net"] }
tokio-tungstenite = "0.26"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
